### ISSUE TITLE
How to query the server?

### ISSUE THREAD

**Issue by Abhijit-2592** [elifesciences/cermine-docker#3]
I am new to this. Can you provide example on how to use cermine as a private service hosted using docker containers

**Comment by de-code** [comment]
Hi, please refer to the main *REST service* section of the [CERMINE README](https://github.com/CeON/CERMINE/blob/master/README.md). But instead of using _cermine.ceon.pl_ you would use the host of where you deployed the docker container. If you had run it via `docker run -p 8072:8080 elifesciences/cermine:1.13` you could use http://localhost:8072/extract.do

**Comment by Abhijit-2592** [comment]
@de-code  Thanks. It worked. I am closing this.
